
EXECUTABLE  := ising
CUFILES     := isingCuda.cu
CU_DEPS     := rand48.cu bits.cpp ising.h
CCFILES     := main.cpp bits.cpp ising.cpp ising1.cpp ising2.cpp
C_DEPS      := ising.h

include ../../common/common.mk
