#!/usr/bin/python

import sys, os

def run (c):
    os.system ('../../bin/linux/release/ising '+c)

if __name__ == '__main__':
    if len(sys.argv) > 1:
        run (' '.join(sys.argv[1:]))
    else:
        run ('1')

