SRCDIR := src/
ROOTDIR := /home/kbarros/cuda/cuda_sdk/projects
ROOTBINDIR := bin


EXECUTABLE	:= qcd
CUFILES		:= qcd.cu
CU_DEPS		:= src/qcd_kernel.cu
CCFILES		:= qcd_gold.cpp

################################################################################
# Rules and targets

include $(ROOTDIR)/../common/common.mk
