
EXECUTABLE	:= dslash
CUFILES_sm_13	:= dslash_cuda.cu blas_cuda.cu
CU_DEPS		:= dslash_core.cu dslash_dagger_core.cu reduce_core.cu qcd.h
CCFILES		:= qcd.cpp blas_reference.cpp dslash_reference.cpp dslash_test.cpp cg_reference.cpp cg_cuda.cpp cg_test.cpp
C_DEPS		:= qcd.h

include ../../common/common.mk
